---
- name: "Build Automated Backend"
  hosts: localhost
  tasks:
  - name : Stop container
    command : sudo docker stop server-container
    ignore_errors: yes

  - name : Remove container
    command : sudo docker rm server-container --force
    ignore_errors: yes

  - name : Remove image
    command : sudo docker rmi server-image --force
    ignore_errors: yes
    
  - name : Build Image
    command : sudo docker build -t server-image .
    
  - name : Run image
    command : sudo docker run -d -p 3000:3000 --name server-container server-image